pipeline{
       agent any
            stages{
	         stage('image_build'){
		                   steps{
				          sh '''
					         echo "building the image" 

						 docker image build -t image2 ${WORKSPACE}/Docker
					     '''
					}

				     }

                 stage('image_tagging'){
		                   steps{
				          sh '''
					         docker image tag image2:latest chanduravi/image2:latest
					     '''
					}

				       }

		 stage('image_pulling'){
		                   steps{
				          sh ''' 
					          docker login -u chanduravi -p Ravi@2021
					          docker image push chanduravi/image2:latest
					     '''
				         }
					}

		 stage('image_deployment'){
		                      steps{
				             sh '''
					            docker container run -it --name c1 chanduravi/image2:latest
						'''


				            }
					   }

		     }


	}	     
						 
